version: '3'

networks:
  default:
    external: true
    name: main

services:
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './certs/:/etc/nginx/certs:ro'
    depends_on:
      - opsrelay

  opsrelay:
    image: opsrelay:latest
    container_name: opsrelay


